# Generated by Django 4.2.4 on 2023-08-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zomato_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='availability',
            new_name='available',
        ),
    ]
